AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 3.2
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/style.yml

inherit_from: .rubocop_todo.yml

# Metrics - disabled globally as they are often too restrictive for domain logic
Metrics:
  Enabled: false

# RSpec - selectively disabled for test readability
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

# Project-specific RSpec settings
RSpec/SpecFilePathFormat:
  CustomTransform:
    TIntMe: tint_me

# Benchmark scripts are allowed to use top-level methods and may not need documentation
Style/TopLevelMethodDefinition:
  Exclude:
    - 'benchmark/**/*'

Style/DocumentationMethod:
  Exclude:
    - 'benchmark/**/*'

