module TIntMe
  VERSION: String

  def self.[]: (
    *Style::positional_arg args,
    ?foreground: Style::color_value?,
    ?background: Style::color_value?,
    ?bold: Style::boolean_value?,
    ?faint: Style::boolean_value?,
    ?italic: Style::boolean_value?,
    ?underline: Style::underline_value?,
    ?overline: Style::boolean_value?,
    ?blink: Style::boolean_value?,
    ?inverse: Style::boolean_value?,
    ?conceal: Style::boolean_value?
  ) -> Style
end
