name: Release Validation

# This workflow validates release PRs before they are merged.
# It performs comprehensive checks on version, dependencies, and release readiness.

env:
  GEM_NAME: ${{ github.event.repository.name }}

on:
  pull_request:
    branches: [main]

jobs:
  validate-release:
    # Only run for release branches
    if: startsWith(github.head_ref, 'release-v')
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required for git tag push

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true

    - name: Extract version from branch name
      id: version
      run: |
        BRANCH_NAME="${{ github.head_ref }}"
        VERSION=${BRANCH_NAME#release-v}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=v$VERSION" >> $GITHUB_OUTPUT

    - name: Validate version format
      run: |
        if ! echo "${{ steps.version.outputs.version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "❌ Error: Version must be in format x.y.z (e.g., 1.0.0)"
          exit 1
        fi

    - name: Verify version consistency
      run: |
        # Check if version in file matches branch
        FILE_VERSION=$(grep 'VERSION = ' lib/${{ env.GEM_NAME }}/version.rb | sed 's/.*VERSION = "\(.*\)".*/\1/')
        if [ "$FILE_VERSION" != "${{ steps.version.outputs.version }}" ]; then
          echo "❌ Error: Version mismatch. File: $FILE_VERSION, Expected: ${{ steps.version.outputs.version }}"
          exit 1
        fi

    - name: Check if git tag already exists
      run: |
        if git tag | grep -q "^${{ steps.version.outputs.tag }}$"; then
          if [ "${{ github.event.action }}" != "synchronize" ]; then
            echo "❌ Error: Git tag ${{ steps.version.outputs.tag }} already exists"
            echo "This should only happen if the tag was created outside the release process"
            exit 1
          else
            echo "Tag ${{ steps.version.outputs.tag }} exists and will be updated to latest commit"
          fi
        fi

    - name: Check if version already released on RubyGems
      run: |
        if gem list ${{ env.GEM_NAME }} --remote | grep -q "${{ steps.version.outputs.version }}"; then
          echo "❌ Error: Version ${{ steps.version.outputs.version }} already exists on RubyGems"
          exit 1
        fi

    - name: Validate RubyGems API key
      env:
        API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        if [ -z "$API_KEY" ]; then
          echo "❌ Error: RUBYGEMS_API_KEY secret is not configured"
          echo ""
          echo "To fix this:"
          echo "1. Generate an API key at https://rubygems.org/profile/edit"
          echo "2. Go to repository Settings -> Secrets and variables -> Actions"
          echo "3. Add new secret: RUBYGEMS_API_KEY with your API key"
          echo ""
          echo "This PR cannot be merged until the secret is configured."
          exit 1
        else
          echo "✅ RUBYGEMS_API_KEY is configured"
        fi

    - name: Validate CHANGELOG.md format
      run: |
        # Check if CHANGELOG has the expected section for this version
        if ! grep -q "^## \[${{ steps.version.outputs.version }}\]" CHANGELOG.md; then
          echo "❌ Error: CHANGELOG.md missing section for version ${{ steps.version.outputs.version }}"
          exit 1
        fi

    - name: Set git user for tag update
      if: github.event.action == 'synchronize'  # When new commits are pushed to PR
      uses: git-actions/set-user@v1

    - name: Update release tag to latest commit
      if: github.event.action == 'synchronize'  # When new commits are pushed to PR
      run: |
        echo "Updating tag v${{ steps.version.outputs.version }} to latest commit"

        # Force update the tag to current HEAD
        git tag -fa "v${{ steps.version.outputs.version }}" \
          -m "Release v${{ steps.version.outputs.version }}"

        # Force push the updated tag
        git push origin "v${{ steps.version.outputs.version }}" --force

        echo "🏷️ Tag v${{ steps.version.outputs.version }} updated to commit $(git rev-parse --short HEAD)"

    - name: Release validation summary
      run: |
        echo "✅ Release validation passed for v${{ steps.version.outputs.version }}"
        echo "- Version format is valid"
        echo "- Version consistency verified"
        echo "- Git tag exists at correct commit"
        echo "- Version not yet on RubyGems"
        echo "- RubyGems API key is configured"
        echo "- CHANGELOG.md is properly formatted"
        echo "- Quality checks handled by CI workflow"
        if [ "${{ github.event.action }}" == "synchronize" ]; then
          echo "- Tag updated to latest commit"
        fi